// Code generated by mockery v2.26.0. DO NOT EDIT.

package allocation

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIPRepository is an autogenerated mock type for the IPRepository type
type MockIPRepository struct {
	mock.Mock
}

type MockIPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPRepository) EXPECT() *MockIPRepository_Expecter {
	return &MockIPRepository_Expecter{mock: &_m.Mock}
}

// GetAllIPs provides a mock function with given fields: ctx
func (_m *MockIPRepository) GetAllIPs(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPRepository_GetAllIPs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllIPs'
type MockIPRepository_GetAllIPs_Call struct {
	*mock.Call
}

// GetAllIPs is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPRepository_Expecter) GetAllIPs(ctx interface{}) *MockIPRepository_GetAllIPs_Call {
	return &MockIPRepository_GetAllIPs_Call{Call: _e.mock.On("GetAllIPs", ctx)}
}

func (_c *MockIPRepository_GetAllIPs_Call) Run(run func(ctx context.Context)) *MockIPRepository_GetAllIPs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIPRepository_GetAllIPs_Call) Return(_a0 []string, _a1 error) *MockIPRepository_GetAllIPs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPRepository_GetAllIPs_Call) RunAndReturn(run func(context.Context) ([]string, error)) *MockIPRepository_GetAllIPs_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockIPRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockIPRepository creates a new instance of MockIPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockIPRepository(t mockConstructorTestingTNewMockIPRepository) *MockIPRepository {
	mock := &MockIPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
