version: "3.7"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    env_file:
      - ".env"
    container_name: dhcpd_db
    volumes:
      - dhcpd-db:/var/lib/postgresql/data
  traefik:
    restart: unless-stopped
    image: traefik:v2.10
    container_name: dhcpd_traefik
    ports:
      - "80:80"
      - "8080:8080"
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    restart: unless-stopped
    build: ../dhcpd-frontend
    container_name: dhcpd_frontend
    labels:
      traefik.http.routers.frontend.rule: "PathPrefix(`/`)"
  backend:
    env_file:
      - ".env"
    restart: unless-stopped
    build: ../backend
    container_name: dhcpd_backend
    labels:
      traefik.http.routers.backend.rule: "PathPrefix(`/dhcpd`)"
    volumes:
      - ./dhcpd.conf:/app/dhcpd.conf
volumes:
  dhcpd-db:
    external: true
