version: "3.8"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    env_file:
      - ".env"
    container_name: dhcp_db
    volumes:
      - dhcp-db:/var/lib/postgresql/data
  traefik:
    restart: unless-stopped
    image: traefik:v2.10
    container_name: dhcp_traefik
    ports:
      - "443:443"
    command:
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    restart: unless-stopped
    build: ../frontend
    container_name: dhcp_frontend
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.tls: true
      traefik.http.routers.frontend.rule: "PathPrefix(`/`)"
  backend:
    env_file:
      - ".env"
    restart: unless-stopped
    build: ../backend
    container_name: dhcp_backend
    depends_on: 
      - database
      - dhcp4
    labels:
      traefik.enable: true
      traefik.http.routers.backend.tls: true
      traefik.http.routers.backend.rule: "PathPrefix(`/dhcp`)"
    volumes:
      - ./user-list.json:/app/user-list.json
  dhcp4:
    container_name: dhcp4-server
    build: kea-dhcp4
    restart: unless-stopped
    ports:
      - "67:67"
    volumes:
      - ./user-list.json:/app/user-list.json
volumes:
  dhcp-db:
    external: true
