version: "3.8"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    env_file:
      - ".env"
    container_name: dhcp_db
    volumes:
      - dhcp-db:/var/lib/postgresql/data
  traefik:
    restart: unless-stopped
    image: traefik:v2.10
    container_name: dhcp_traefik
    ports:
      - "443:443"
    command:
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=default"
      - "--log.level=DEBUG"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    restart: unless-stopped
    build: ../frontend
    container_name: dhcp_frontend
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.tls: true
      traefik.http.routers.frontend.rule: "PathPrefix(`/`)"
  backend:
    env_file:
      - ".env"
    restart: unless-stopped
    build: ../backend
    container_name: dhcp_backend
    depends_on:
      - database
      - dhcp4
    labels:
      traefik.enable: true
      traefik.http.routers.backend.tls: true
      traefik.http.routers.backend.rule: "PathPrefix(`/api`)"
    networks:
      - default
      - kea-10-ipvlan
    volumes:
      - ./whitelist.json:/app/whitelist.json
      - ./login-users.json:/app/login-users.json
  dhcp4:
    container_name: dhcp4-server
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.4.1
    restart: unless-stopped
    networks:
      - kea-10-ipvlan
    volumes:
      - ./whitelist.json:/app/whitelist.json
      - ./kea-dhcp4:/etc/kea
      - kea4-var:/var/lib/kea
volumes:
  dhcp-db:
    external: true
  kea4-var:

networks:
  kea-10-ipvlan: # network that binds container to host network interface.
    name: kea-10-ipvlan
    driver: ipvlan
    driver_opts:
      parent: eno1 #  host interface that kea containers will use !!!!!!
    ipam:
      config:
        - subnet: 149.201.243.0/24 # subnet for kea4 server
