version: "3.7"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: network
      POSTGRES_PASSWORD: network
      POSTGRES_DB: network
    container_name: dhcpd_db
    ports:
      - 5432:5432
    volumes:
      - dhcpd-db
  traefik:
    restart: unless-stopped
    image: traefik:v2.10
    container_name: dhcpd_traefik
    ports:
      - 8000:8000
  frontend:
    restart: unless-stopped
    build: ../dhcpd-frontend
    container_name: dhcpd_frontend
  backend:
    restart: unless-stopped
    build: ../backend      
    container_name: dhcpd_backend
volumes:
  dhcpd-db:
