name: dhcp
services:
  database:
    restart: unless-stopped
    image: postgres:15
    env_file:
      - ".env"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 10s
      start_period: 20s
    container_name: dhcp_db
    networks:
      - traefik
    volumes:
      - dhcp-db:/var/lib/postgresql/data
    expose:
      - "5432"
  traefik:
    restart: unless-stopped
    image: traefik:v3.4
    container_name: dhcp_traefik
    networks:
      - traefik
    ports:
      - "443:443"
    command:
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      - "--log.level=DEBUG"
      - "--entrypoints.websecure.address=:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    restart: unless-stopped
    build: ../frontend
    container_name: dhcp_frontend
    labels:
      traefik.enable: true
      traefik.http.routers.frontend.tls: true
      traefik.http.routers.frontend.rule: "PathPrefix(`/`)"
    networks:
      - traefik
    expose:
      - "3000/tcp"
  backend:
    env_file:
      - ".env"
    restart: unless-stopped
    build: ../backend
    container_name: dhcp_backend
    depends_on:
      database:
        condition: service_healthy
      dhcp4:
        condition: service_healthy
    labels:
      traefik.enable: true
      traefik.docker.network: "traefik"
      traefik.http.routers.backend.tls: true
      traefik.http.routers.backend.rule: "PathPrefix(`/api`)"
    networks:
      - traefik
      - kea-cmd
    expose:
      - "8080/tcp"
    volumes:
      - ./whitelist.json:/app/whitelist.json
      - ./login-users.json:/app/login-users.json
  dhcp4:
    container_name: dhcp4-server
    image: docker.cloudsmith.io/isc/docker/kea-dhcp4:2.6.2
    restart: unless-stopped
    networks:
      - kea-lan
      - kea-cmd
    volumes:
      - ./whitelist.json:/app/whitelist.json
      - ./kea-dhcp4:/etc/kea
      - kea4-var:/var/lib/kea
volumes:
  dhcp-db:
    external: true
  kea4-var:

networks:
  traefik:
    name: traefik
    external: true
  kea-cmd:
    name: kea-cmd
  kea-lan: # network that binds container to host network interface.
    name: kea-10-ipvlan
    driver: ipvlan
    driver_opts:
      parent: eno1 #  host interface that kea containers will use !!!!!!
    ipam:
      config:
        - subnet: 149.201.243.0/24 # subnet for kea4 server
