version: "3.7"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    env_file:
      - ".env"
    container_name: dhcp_db
    volumes:
      - dhcp-db:/var/lib/postgresql/data
  traefik:
    restart: unless-stopped
    image: traefik:v2.10
    container_name: dhcp_traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command: --api.insecure=true --providers.docker --log.level=DEBUG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    restart: unless-stopped
    build: ../frontend
    container_name: dhcp_frontend
    labels:
      traefik.http.routers.frontend.rule: "PathPrefix(`/`)"
  backend:
    env_file:
      - ".env"
    restart: unless-stopped
    build: ../backend
    container_name: dhcp_backend
    labels:
      traefik.http.routers.backend.rule: "PathPrefix(`/dhcp`)"
    volumes:
      - ../user-list.json:/app/user-list.json
volumes:
  dhcp-db:
    external: true
