version: "3.7"

services:
  database:
    restart: unless-stopped
    image: postgres:15
    environment:
      POSTGRES_USER: network
      POSTGRES_PASSWORD: network
      POSTGRES_DB: network
    container_name: internet-db
    ports:
      - 5432:5432
    volumes:
      - internet-db:/var/lib/postgresql/data
volumes:
  internet-db: